In [57]:
from math import factorial as fl
import numpy as np

In [58]:
def C(k,n):
    return int(fl(n) / (fl(k) * fl(n-k)))

Задача 1
Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите M(X), D(X).

Из 20 вариантов ответов выбираем 5 ответов (по одному на вопрос), тогда общее число сочетаний: 

In [59]:
C(5,20)

15504

У нас могут быть следующие события: X - правильный ответ на: 0, 1, 2, 3, 4, 5 вопросов.

In [60]:
x_values = np.arange(0, 6)
print(x_values)

[0 1 2 3 4 5]


Тогда вероятности каждого события будут следующие:

In [61]:
x_probabilities = np.array([])

In [62]:
x_probabilities = np.append(x_probabilities, [C(0,5) * C(5,15) / C(5,20)])

In [63]:
x_probabilities = np.append(x_probabilities, [C(1,5) * C(4,15) / C(5,20)])

In [64]:
x_probabilities = np.append(x_probabilities, [C(2,5) * C(3,15) / C(5,20)])

In [65]:
x_probabilities = np.append(x_probabilities, [C(3,5) * C(2,15) / C(5,20)])

In [66]:
x_probabilities = np.append(x_probabilities, [C(4,5) * C(1,15) / C(5,20)])

In [67]:
x_probabilities = np.append(x_probabilities, [C(5,5) * C(0,15) / C(5,20)])

In [68]:
x_probabilities

array([1.93691950e-01, 4.40208978e-01, 2.93472652e-01, 6.77244582e-02,
       4.83746130e-03, 6.44994840e-05])

In [69]:
m = x_values.dot(x_probabilities)
m

1.25

In [70]:
y_values = x_values - m
print(y_values)

[-1.25 -0.25  0.75  1.75  2.75  3.75]


In [55]:
z_values = y_values ** 2
print(z_values)

[ 1.5625  0.0625  0.5625  3.0625  7.5625 14.0625]


In [56]:
d = z_values.dot(x_probabilities)
print(d)

0.7401315789473684


In [ ]:
Ответ: математическое ожидание = 1.25, дисперсия = 0.74013

Задача 2
Вероятность попадания в цель при одном выстреле равна 0.01. Какова вероятность того, что число попаданий при 200 выстрелах будет не менее 5 и не более 10?